import "./styles.css"
import "./fonts/beau-rivage/stylesheet.css"
import "./fonts/boldnose/stylesheet.css"
import "./fonts/mea-culpa/stylesheet.css"
import "./fonts/merriweather/stylesheet.css"
import "./fonts/roboto/stylesheet.css"
import "./markup.js"
import "./dom.js"